name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Verify API_KEY
        run: echo $API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm test
